# Generated by Django 3.0.8 on 2020-08-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('People', models.IntegerField()),
                ('Task', models.CharField(max_length=20)),
            ],
        ),
    ]
